apiVersion: v1
data:
  halconfig: |
    {
      "name": "default",
      "version": "1.14.8",
      "providers": {
        "appengine": {
          "enabled": false,
          "accounts": []
        },
        "aws": {
          "enabled": true,
          "accounts": [
            {
              "name": "my-aws-ec2-account",
              "requiredGroupMembership": [],
              "providerVersion": "V1",
              "permissions": {},
              "accountId": "732813442182",
              "regions": [
                {
                  "name": "us-west-2"
                }
              ],
              "assumeRole": "role/spinnakerManaged"
            },
            {
              "name": "ec2account",
              "requiredGroupMembership": [],
              "providerVersion": "V1",
              "permissions": {},
              "accountId": "732813442182",
              "regions": [
                {
                  "name": "us-west-2"
                }
              ],
              "assumeRole": "role/spinnakerManaged"
            }
          ],
          "bakeryDefaults": {
            "baseImages": []
          },
          "defaultKeyPairTemplate": "{{name}}-keypair",
          "defaultRegions": [
            {
              "name": "us-west-2"
            },
            {
              "name": "us-east-1"
            }
          ],
          "defaults": {
            "iamRole": "BaseIAMRole"
          },
          "primaryAccount": "my-aws-ec2-account",
          "accessKeyId": "<Your-AWS-key>",
          "secretAccessKey": "<Your-AWS-accesskey>"
        },
        "ecs": {
          "enabled": false,
          "accounts": [
            {
              "name": "ecs-spinnaker",
              "requiredGroupMembership": [],
              "providerVersion": "V1",
              "permissions": {},
              "awsAccount": "ec2account"
            }
          ],
          "primaryAccount": "ecs-spinnaker"
        },
        "azure": {
          "enabled": false,
          "accounts": [],
          "bakeryDefaults": {
            "templateFile": "azure-linux.json",
            "baseImages": []
          }
        },
        "dcos": {
          "enabled": false,
          "accounts": [],
          "clusters": []
        },
        "dockerRegistry": {
          "enabled": true,
          "accounts": [
            {
              "name": "my-docker-registry",
              "requiredGroupMembership": [],
              "providerVersion": "V1",
              "permissions": {},
              "address": "https://index.docker.io",
              "username": "opsmx11",
              "password": "<Your-docker-pass>",
              "email": "actual.email@spinnaker.io",
              "cacheIntervalSeconds": 30,
              "clientTimeoutMillis": 60000,
              "cacheThreads": 1,
              "paginateSize": 100,
              "sortTagsByDate": false,
              "trackDigests": false,
              "insecureRegistry": false,
              "repositories": [
                "opsmx11/restapp"
              ]
            }
          ],
          "primaryAccount": "my-docker-registry"
        },
        "google": {
          "enabled": false,
          "accounts": [],
          "bakeryDefaults": {
            "templateFile": "gce.json",
            "baseImages": [],
            "zone": "us-central1-f",
            "network": "default",
            "useInternalIp": false
          }
        },
        "kubernetes": {
          "enabled": true,
          "accounts": [
            {
              "name": "openshift1-account",
              "requiredGroupMembership": [],
              "providerVersion": "V2",
              "permissions": {},
              "dockerRegistries": [],
              "configureImagePullSecrets": true,
              "cacheThreads": 1,
              "namespaces": [
                "default",
                "arihant"
              ],
              "omitNamespaces": [],
              "kinds": [],
              "omitKinds": [
                "podPreset"
              ],
              "customResources": [],
              "cachingPolicies": [],
              "kubeconfigFile": "/home/opsmxgcetest/.kube/config",
              "liveManifestCalls": true,
              "oAuthScopes": [],
              "onlySpinnakerManaged": false,
              "context": "default/35-237-183-196:8443/CN=sagnik,CN=Users,DC=local,DC=opsmx,DC=com",
              "checkPermissionsOnStartup": false
            },
            {
              "name": "my-k8s-v2-account",
              "requiredGroupMembership": [],
              "providerVersion": "V2",
              "permissions": {},
              "dockerRegistries": [],
              "configureImagePullSecrets": true,
              "cacheThreads": 1,
              "namespaces": [],
              "omitNamespaces": [],
              "kinds": [],
              "omitKinds": [],
              "customResources": [],
              "cachingPolicies": [],
              "kubeconfigFile": "/home/opsmxgcetest/.kube/config",
              "liveManifestCalls": true,
              "oAuthScopes": [],
              "onlySpinnakerManaged": false,
              "context": "gke_my-orbit-project-71824_us-central1-a_gke-standard-cluster"
            },
            {
              "name": "devk8s-v2local",
              "requiredGroupMembership": [],
              "providerVersion": "V2",
              "permissions": {},
              "dockerRegistries": [],
              "configureImagePullSecrets": true,
              "cacheThreads": 1,
              "namespaces": [],
              "omitNamespaces": [],
              "kinds": [],
              "omitKinds": [],
              "customResources": [],
              "cachingPolicies": [],
              "kubeconfigFile": "/home/opsmxgcetest/.kube/devk8slocal",
              "liveManifestCalls": true,
              "oAuthScopes": [],
              "onlySpinnakerManaged": false
            },
            {
              "name": "spin-v2-ekscluster",
              "requiredGroupMembership": [],
              "providerVersion": "V2",
              "permissions": {},
              "dockerRegistries": [],
              "context": "aws",
              "configureImagePullSecrets": true,
              "cacheThreads": 1,
              "namespaces": [],
              "omitNamespaces": [],
              "kinds": [],
              "omitKinds": [],
              "customResources": [],
              "cachingPolicies": [],
              "kubeconfigFile": "/home/opsmxgcetest/.kube/spineksconfig",
              "liveManifestCalls": true,
              "oAuthScopes": [],
              "onlySpinnakerManaged": false
            }
          ],
          "primaryAccount": "openshift1-account"
        },
        "oracle": {
          "enabled": false,
          "accounts": [],
          "bakeryDefaults": {
            "templateFile": "oci.json",
            "baseImages": []
          }
        },
        "cloudfoundry": {
          "enabled": false,
          "accounts": []
        }
      },
      "deploymentEnvironment": {
        "size": "SMALL",
        "type": "LocalDebian",
        "updateVersions": true,
        "consul": {
          "enabled": false
        },
        "vault": {
          "enabled": false
        },
        "customSizing": {},
        "sidecars": {},
        "initContainers": {},
        "hostAliases": {},
        "affinity": {},
        "nodeSelectors": {},
        "gitConfig": {
          "upstreamUser": "spinnaker"
        },
        "livenessProbeConfig": {
          "enabled": false
        },
        "haServices": {
          "clouddriver": {
            "enabled": false,
            "disableClouddriverRoDeck": true
          },
          "echo": {
            "enabled": false
          }
        }
      },
      "persistentStorage": {
        "persistentStoreType": "gcs",
        "azs": {},
        "gcs": {
          "jsonPath": "/home/opsmxgcetest/.gcp/gcp-account.json",
          "bucket": "ops-demo-spinnakers",
          "rootFolder": "front50",
          "project": "my-orbit-project-71824"
        },
        "redis": {},
        "s3": {
          "bucket": "istio1",
          "rootFolder": "front50",
          "region": "us-west-2",
          "accessKeyId": "<Your-AWS-keyID>",
          "secretAccessKey": "<Your-AWS-key>"
        },
        "oracle": {}
      },
      "features": {
        "auth": false,
        "fiat": false,
        "chaos": false,
        "entityTags": false,
        "jobs": false,
        "pipelineTemplates": true,
        "managedPipelineTemplatesV2UI": true,
        "artifacts": true,
        "mineCanary": true
      },
      "metricStores": {
        "datadog": {
          "enabled": false,
          "tags": []
        },
        "prometheus": {
          "enabled": false,
          "add_source_metalabels": true
        },
        "stackdriver": {
          "enabled": false
        },
        "period": 30,
        "enabled": false
      },
      "notifications": {
        "slack": {
          "enabled": false
        },
        "twilio": {
          "enabled": false,
          "baseUrl": "https://api.twilio.com/"
        }
      },
      "timezone": "America/Los_Angeles",
      "ci": {
        "jenkins": {
          "enabled": true,
          "masters": [
            {
              "name": "my-jenkins-master",
              "permissions": {},
              "address": "http://<Your-jenkins-url>:8181/jenkins",
              "username": "opsmx",
              "password": "<Your-jenkins-pass>"
            }
          ]
        },
        "travis": {
          "enabled": false,
          "masters": []
        },
        "wercker": {
          "enabled": false,
          "masters": []
        },
        "concourse": {
          "enabled": false,
          "masters": []
        },
        "gcb": {
          "enabled": false,
          "accounts": []
        }
      },
      "repository": {
        "artifactory": {
          "enabled": false,
          "searches": []
        }
      },
      "security": {
        "apiSecurity": {
          "ssl": {
            "enabled": false
          },
          "overrideBaseUrl": "<Your-spinnakerapi-url>"
        },
        "uiSecurity": {
          "ssl": {
            "enabled": false
          },
          "overrideBaseUrl": "<Your-spinnakerUI-url>"
        },
        "authn": {
          "oauth2": {
            "enabled": false,
            "client": {},
            "resource": {},
            "userInfoMapping": {}
          },
          "saml": {
            "enabled": false,
            "userAttributeMapping": {}
          },
          "ldap": {
            "enabled": true,
            "url": "ldap://<Your-ldap-url>:389",
            "userDnPattern": "CN={0},CN=Users,dc=local,dc=opsmx,dc=com"
          },
          "x509": {
            "enabled": false
          },
          "iap": {
            "enabled": false
          },
          "enabled": true
        },
        "authz": {
          "groupMembership": {
            "service": "EXTERNAL",
            "google": {
              "roleProviderType": "GOOGLE"
            },
            "github": {
              "roleProviderType": "GITHUB"
            },
            "file": {
              "roleProviderType": "FILE"
            },
            "ldap": {
              "roleProviderType": "LDAP"
            }
          },
          "enabled": true
        }
      },
      "artifacts": {
        "bitbucket": {
          "enabled": true,
          "accounts": [
            {
              "name": "bitbucket-account",
              "username": "sher-locked",
              "password": "<Your-bitbucket-pass>"
            }
          ]
        },
        "gcs": {
          "enabled": false,
          "accounts": []
        },
        "oracle": {
          "enabled": false,
          "accounts": []
        },
        "github": {
          "enabled": true,
          "accounts": [
            {
              "name": "OpsMx-demoGit",
              "username": "OpsMx",
              "token": "<Your-git-token>"
            }
          ]
        },
        "gitlab": {
          "enabled": false,
          "accounts": []
        },
        "http": {
          "enabled": false,
          "accounts": []
        },
        "helm": {
          "enabled": false,
          "accounts": []
        },
        "s3": {
          "enabled": false,
          "accounts": []
        },
        "maven": {
          "enabled": false,
          "accounts": []
        },
        "templates": []
      },
      "pubsub": {
        "enabled": false,
        "google": {
          "enabled": false,
          "pubsubType": "GOOGLE",
          "subscriptions": [],
          "publishers": []
        }
      },
      "canary": {
        "enabled": true,
        "serviceIntegrations": [
          {
            "name": "google",
            "enabled": true,
            "accounts": [
              {
                "name": "<Your-google-name>",
                "project": "<Your-project-name>4",
                "jsonPath": "/home/opsmxgcetest/.gcp/gcp-account.json",
                "bucket": "kayentagcpbucket",
                "rootFolder": "kayenta",
                "supportedTypes": [
                  "CONFIGURATION_STORE",
                  "OBJECT_STORE"
                ]
              }
            ],
            "gcsEnabled": true,
            "stackdriverEnabled": false
          },
          {
            "name": "prometheus",
            "enabled": true,
            "accounts": [
              {
                "name": "prometheus-account",
                "endpoint": {
                  "baseUrl": "http://<Your-prometheus-url>:9090"
                },
                "supportedTypes": [
                  "METRICS_STORE"
                ]
              }
            ]
          },
          {
            "name": "datadog",
            "enabled": false,
            "accounts": []
          },
          {
            "name": "aws",
            "enabled": false,
            "accounts": [],
            "s3Enabled": false
          }
        ],
        "reduxLoggerEnabled": true,
        "defaultJudge": "NetflixACAJudge-v1.0",
        "stagesEnabled": true,
        "templatesEnabled": true,
        "showAllConfigsEnabled": true,
        "defaultMetricsStore": "prometheus"
      },
      "webhook": {
        "trust": {
          "enabled": false
        }
      }
    }
kind: ConfigMap
metadata:
  name: terraspinhalconfig

