apiVersion: v1
kind: Service
metadata:
  name: opsmx-terraspin-service
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: opsmx-terraspin
